"""cdk-nag suppressions with written justifications.

Imported only when the nag scan is enabled (`cdk synth -c nag=true`), so
cdk-nag is never a dependency of the normal deploy path.

Every suppression below records *why* the finding is accepted. These are
deliberate, reviewable decisions — not blanket silencing. Anything that could
be remediated safely has been remediated instead (DynamoDB PITR, S3 server
access logging, Step Functions ALL-event logging and X-Ray, Lambda and API
Gateway X-Ray tracing, API Gateway stage throttling).

The suppressions fall into three groups:

  1. NOT REMEDIABLE in the current architecture (CFR4).
  2. DEFERRED because remediating carries a real breakage risk that outweighs
     the benefit for a proof of concept (L1 / LambdaLatestVersion, CFR7).
  3. ACCEPTED as known proof-of-concept limitations, already documented in
     README.md and SECURITY.md (no authentication, broad IAM, no WAF).

Group 3 is the reason this tool must not be used in production.
"""

from __future__ import annotations

from cdk_nag import NagSuppressions

_STACK = "ConnectAcgrReplicatorStack"


def apply(stack) -> None:
    """Attach all justified suppressions to the stack."""

    def suppress(path: str, items: list[dict], apply_to_children: bool = False) -> None:
        NagSuppressions.add_resource_suppressions_by_path(
            stack,
            f"/{_STACK}/{path}",
            items,
            apply_to_children=apply_to_children,
        )

    # ------------------------------------------------------------------
    # IAM — broad permissions (ACCEPTED: documented PoC limitation)
    # ------------------------------------------------------------------
    suppress(
        "ReplicatorLambdaRole/Resource",
        [{
            "id": "AwsSolutions-IAM4",
            "reason": (
                "Uses the AWS managed policy AWSLambdaBasicExecutionRole for CloudWatch "
                "Logs write access only. This is the AWS-recommended baseline execution "
                "policy and is narrower than an equivalent hand-written inline policy. "
                "No data-plane or administrative managed policies are attached."
            ),
        }],
    )
    suppress(
        "ReplicatorApi/CloudWatchRole/Resource",
        [{
            "id": "AwsSolutions-IAM4",
            "reason": (
                "Role and managed policy (AmazonAPIGatewayPushToCloudWatchLogs) are "
                "created automatically by the AWS CDK ApiGateway construct to enable "
                "stage access logging. Not author-controlled; removing it would disable "
                "the access logging this review requires."
            ),
        }],
    )
    suppress(
        "ReplicatorLambdaRole/DefaultPolicy/Resource",
        [{
            "id": "AwsSolutions-IAM5",
            "reason": (
                "Wildcard resources are inherent to the tool's function and are "
                "ACCEPTED for this proof of concept. The tool discovers and replicates "
                "arbitrary, caller-selected Amazon Connect dependencies (AWS Lambda, "
                "Amazon Lex, Amazon Kinesis Data Streams, Amazon Data Firehose, Amazon "
                "Kinesis Video Streams, Amazon S3, AWS IAM, Amazon Q in Connect) across "
                "two AWS Regions. The target resource ARNs are not knowable at synth "
                "time, so they cannot be enumerated in the policy. A wildcard is also "
                "required by AWS X-Ray (xray:PutTraceSegments / "
                "xray:PutTelemetryRecords do not support resource-level permissions). "
                "This role is NOT least-privilege and is explicitly called out as a "
                "production blocker in README.md and SECURITY.md. Production use "
                "requires scoping to a known resource inventory."
            ),
        }],
    )
    suppress(
        "ReplicationStateMachine/Role/DefaultPolicy/Resource",
        [{
            "id": "AwsSolutions-IAM5",
            "reason": (
                "Generated by the AWS CDK StateMachine construct. The wildcard is on "
                "the Lambda invoke grant (function version/alias qualifiers) and on "
                "X-Ray and CloudWatch Logs actions, which do not support "
                "resource-level permissions. Not author-controlled."
            ),
        }],
    )

    # ------------------------------------------------------------------
    # API Gateway — no authentication (ACCEPTED: documented PoC limitation)
    # ------------------------------------------------------------------
    for method_path in (
        "ReplicatorApi/Default/ANY/Resource",
        "ReplicatorApi/Default/{proxy+}/ANY/Resource",
    ):
        suppress(
            method_path,
            [
                {
                    "id": "AwsSolutions-APIG4",
                    "reason": (
                        "ACCEPTED, KNOWN PROOF-OF-CONCEPT LIMITATION. The API "
                        "intentionally has no authorizer so the tool can be deployed "
                        "and demonstrated without an identity provider. This is the "
                        "single highest residual risk in this project: anyone who can "
                        "reach the endpoint can trigger resource replication and "
                        "deletion. It is documented prominently in README.md and "
                        "SECURITY.md, and the tool is restricted to non-production AWS "
                        "accounts and non-production Amazon Connect instances. Adding "
                        "authentication is a mandatory prerequisite for any wider use."
                    ),
                },
                {
                    "id": "AwsSolutions-COG4",
                    "reason": (
                        "No Amazon Cognito user pool is provisioned, for the same "
                        "reason as AwsSolutions-APIG4 above. Amazon Cognito (or an IAM "
                        "/ Lambda authorizer) is the recommended remediation and is "
                        "tracked as a production prerequisite."
                    ),
                },
            ],
        )
    suppress(
        "ReplicatorApi/Resource",
        [{
            "id": "AwsSolutions-APIG2",
            "reason": (
                "Request validation is not configured at the API Gateway layer because "
                "this is a Lambda proxy integration: all routing and validation happen "
                "in the FastAPI application, which validates every request body and "
                "path parameter with Pydantic models and dedicated ARN format "
                "validators, rejecting malformed input with HTTP 422/400. Duplicating "
                "the schema in API Gateway would add a second source of truth without "
                "improving the security posture."
            ),
        }],
    )
    suppress(
        "ReplicatorApi/DeploymentStage.prod/Resource",
        [{
            "id": "AwsSolutions-APIG3",
            "reason": (
                "No AWS WAFv2 web ACL is attached. ACCEPTED for a proof of concept "
                "that is not internet-facing for production traffic and is restricted "
                "to non-production accounts. Stage-level throttling (1000 rps / 2000 "
                "burst) is enabled as a partial mitigation. AWS WAF is recommended "
                "alongside authentication before any production use."
            ),
        }],
    )

    # ------------------------------------------------------------------
    # CloudFront
    # ------------------------------------------------------------------
    suppress(
        "ReplicatorDistribution/Resource",
        [
            {
                "id": "AwsSolutions-CFR4",
                "reason": (
                    "NOT REMEDIABLE in this architecture. The distribution uses the "
                    "default CloudFront certificate (*.cloudfront.net) because it has "
                    "no custom domain. Per AWS documentation, a distribution using the "
                    "default CloudFront certificate is fixed to the TLSv1 security "
                    "policy; MinimumProtocolVersion only takes effect when a custom "
                    "SSL/TLS certificate and alternate domain name (CNAME) are "
                    "configured. Remediation therefore requires provisioning a custom "
                    "domain and an AWS Certificate Manager certificate, which is out of "
                    "scope for this proof of concept. Note that CloudFront still "
                    "negotiates the most secure protocol the viewer supports, and TLS "
                    "1.3 is enabled on all distributions by default."
                ),
            },
            {
                "id": "AwsSolutions-CFR7",
                "reason": (
                    "DEFERRED. The S3 origin is protected by an origin access identity "
                    "(OAI) rather than origin access control (OAC). The bucket blocks "
                    "all public access and is reachable only through CloudFront, so "
                    "origin access is correctly restricted today. OAC is the current "
                    "AWS recommendation and is a tracked follow-up; migrating a live "
                    "distribution from OAI to OAC rewrites both the origin "
                    "configuration and the bucket policy, so it is being scheduled as "
                    "a discrete, verified change rather than bundled with unrelated "
                    "hardening. The functional gaps OAC addresses (SSE-KMS origins, "
                    "dynamic PUT/DELETE requests, Regions launched after January 2023) "
                    "do not apply to this static, GET-only, SSE-S3 frontend in "
                    "us-east-1."
                ),
            },
            {
                "id": "AwsSolutions-CFR1",
                "reason": (
                    "No geographic restrictions. The tool is an internal operator "
                    "console with no geography-based access requirement; restricting by "
                    "country would not add a meaningful control and could block "
                    "legitimate operators."
                ),
            },
            {
                "id": "AwsSolutions-CFR2",
                "reason": (
                    "No AWS WAF integration, for the same reason as AwsSolutions-APIG3. "
                    "ACCEPTED for a non-production proof of concept; recommended "
                    "alongside authentication before production use."
                ),
            },
        ],
    )

    # ------------------------------------------------------------------
    # Lambda — runtime version and DLQ
    # ------------------------------------------------------------------
    for fn_path in ("ReplicatorBackend/Resource", "ResourceReplicatorLambda/Resource"):
        suppress(
            fn_path,
            [
                {
                    "id": "AwsSolutions-L1",
                    "reason": (
                        "DEFERRED for deployment safety. The functions run Python 3.12, "
                        "which is a currently supported AWS Lambda runtime and is not "
                        "deprecated. The deployment bundles third-party dependencies as "
                        "pre-built wheels pinned to cp312 / manylinux2014_x86_64 (see "
                        "deploy.sh: --python-version 3.12 --platform "
                        "manylinux2014_x86_64 --only-binary=:all:). Changing the "
                        "runtime without simultaneously rebuilding and revalidating "
                        "every compiled dependency (for example pydantic-core) would "
                        "cause import failures at runtime and break the deployed "
                        "application. The runtime upgrade is tracked as a coordinated "
                        "change: bump the runtime and the bundling target together, "
                        "then verify. Deferring carries no security exposure while the "
                        "runtime remains supported."
                    ),
                },
                {
                    "id": "Serverless-LambdaLatestVersion",
                    "reason": "Same as AwsSolutions-L1 above — coordinated runtime and dependency-bundling upgrade, deferred for deployment safety.",
                },
                {
                    "id": "Serverless-LambdaDLQ",
                    "reason": (
                        "No dead letter queue is configured. Both functions are invoked "
                        "synchronously in normal operation — the backend by API Gateway "
                        "(request/response) and the resource replicator by AWS Step "
                        "Functions, which provides its own retry and error handling per "
                        "state. The one asynchronous path (the backend self-invoking for "
                        "long-running replication) records per-resource outcomes in "
                        "Amazon DynamoDB, which the UI surfaces and can retry, so failed "
                        "work is neither silently lost nor invisible to the operator. A "
                        "DLQ would add defence in depth and is a tracked enhancement, "
                        "not a security finding."
                    ),
                },
            ],
        )
